config/routes.rb
Rails.application.routes.draw do

 

  devise_for :users, :controllers => {sessions: 'user/sessions', registrations: 'user/registrations', passwords: 'user/passwords' } 

  namespace :api do
    namespace :v1 do
      resources :articles, :defaults => { :format => 'json' }
      resources :players, :defaults => { :format => 'json' } # xml
      resources :player_seasons, :defaults => { :format => 'json' }
      resources :player_badges, :defaults => { :format => 'json' }
      resources :teams, :defaults => { :format => 'json' } # xml
      resources :team_seasons, :defaults => { :format => 'json' }
      resources :home_teams, :defaults => { :format => 'json' }
      resources :away_teams, :defaults => { :format => 'json' }
      resources :team_badges, :defaults => { :format => 'json' }
      resources :delegates, :defaults => { :format => 'json' }
      resources :matches, :defaults => { :format => 'json' }
      resources :goals, :defaults => { :format => 'json' }
      resources :assists, :defaults => { :format => 'json' }
      resources :fouls, :defaults => { :format => 'json' }
      resources :yellow_cards, :defaults => { :format => 'json' }
      resources :red_cards, :defaults => { :format => 'json' }
      resources :goalkeeper_saves, :defaults => { :format => 'json' }
      resources :shoots, :defaults => { :format => 'json' }
      post 'new_home_shoot', to: 'shoots#new_home', :defaults => { :format => 'json' }
      post 'new_away_shoot', to: 'shoots#new_away', :defaults => { :format => 'json' }
      put 'change_match_started', to: 'matches#change_match_started', :defaults => { :format => 'json' }
      patch 'change_match_started', to: 'matches#change_match_started', :defaults => { :format => 'json' }
      put 'change_first_half_ended', to: 'matches#change_first_half_ended', :defaults => { :format => 'json' }
      patch 'change_first_half_ended', to: 'matches#change_first_half_ended', :defaults => { :format => 'json' }
      put 'change_second_half_started', to: 'matches#change_second_half_started', :defaults => { :format => 'json' }
      patch 'change_second_half_started', to: 'matches#change_second_half_started', :defaults => { :format => 'json' }
      put 'change_second_half_ended', to: 'matches#change_second_half_ended', :defaults => { :format => 'json' }
      patch 'change_second_half_ended', to: 'matches#change_second_half_ended', :defaults => { :format => 'json' }
      resources :match_players, :defaults => { :format => 'json' }
      post 'chooseplayers', to: 'match_players#chooseplayers', :defaults => { :format => 'json' }
      resources :players_rang_list, :defaults => { :format => 'json' }
      get 'players_rang_list', to: 'players_rang_list#index', :defaults => { :format => 'json'}
      get 'players_rang_list_4_1', to: 'players_rang_list#index4plus1', :defaults => { :format => 'json'}
      resources :teams_rang_list, :defaults => { :format => 'json' }
      get 'teams_rang_list', to: 'teams_rang_list#index', :defaults => { :format => 'json' }
      get 'teams_rang_list_4_1', to: 'teams_rang_list#index4plus1', :defaults => { :format => 'json' }
      resources :leagues, :defaults => { :format => 'json' }
    end   
  end

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'

  mount Commontator::Engine => '/commontator'
  
   resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]
  get 'messages/new'

  resources :contactmessages, only: [:new, :create]
  

  resources :home_teams

  resources :away_teams

  resources :stadions

  resources :referees

  resources :livescores

  resources :matches do
    member do
      put 'change_match_started', to: 'matches#change_match_started'
      patch 'change_match_started', to: 'matches#change_match_started'

      put 'change_first_half_ended', to: 'matches#change_first_half_ended'
      patch 'change_first_half_ended', to: 'matches#change_first_half_ended'

      put 'change_second_half_started', to: 'matches#change_second_half_started'
      patch 'change_second_half_started', to: 'matches#change_second_half_started'

      put 'change_second_half_ended', to: 'matches#change_second_half_ended'
      patch 'change_second_half_ended', to: 'matches#change_second_half_ended'
    end
  end

  resources :leagues
  
  get 'four_plus_one_leagues', to: 'leagues#fourplusone'
  get 'five_plus_one_leagues', to: 'leagues#fiveplusone'
  resources :team_seasons

  resources :player_seasons

  resources :stats

  resources :results

  resources :seasons

  get 'new_home_players', to: 'match_players#new_home', via: :post
  get 'new_away_players', to: 'match_players#new_away', via: :post
  post 'chooseplayers', to: 'match_players#chooseplayers'

  resources :goals
  get 'new_home_goal', to: 'goals#new_home', via: :post
  get 'new_away_goal', to: 'goals#new_away', via: :post

  resources :assists
  get 'new_home_assist', to: 'assists#new_home', via: :post
  get 'new_away_assist', to: 'assists#new_away', via: :post

  resources :fouls
  get 'new_home_foul', to: 'fouls#new_home', via: :post
  get 'new_away_foul', to: 'fouls#new_away', via: :post

  resources :yellow_cards
  get 'new_home_yellow_card', to: 'yellow_cards#new_home', via: :post
  get 'new_away_yellow_card', to: 'yellow_cards#new_away', via: :post

  resources :red_cards
  get 'new_home_red_card', to: 'red_cards#new_home', via: :post
  get 'new_away_red_card', to: 'red_cards#new_away', via: :post

  resources :shoots
  get 'new_home_shoot', to: 'shoots#new_home', via: :post
  get 'new_away_shoot', to: 'shoots#new_away', via: :post

  resources :goalkeeper_saves
  get 'new_home_goalkeeper_save', to: 'goalkeeper_saves#new_home', via: :post
  get 'new_away_goalkeeper_save', to: 'goalkeeper_saves#new_away', via: :post

  get 'league_seasons/index'
  get 'league_seasons/new'
  get 'league_seasons/create'
  get 'league_seasons/edit'
  get 'league_seasons/update'
  get 'league_seasons/show'

  resources :league_pages

  resources :goalkeeper_saves
  get 'new_home_goalkeeper_save', to: 'goalkeeper_saves#new_home', via: :post
  get 'new_away_goalkeeper_save', to: 'goalkeeper_saves#new_away', via: :post

  get 'rankings/index'
  get 'rankings/show'
  get 'rankings/update'
  get 'rankings/teams'
  get 'rankings/players'

  get 'players_rang_list', to: 'players_rang_list#index'
  get 'players_rang_list_4_1', to: 'players_rang_list#index4plus1'

  get 'teams_rang_list', to: 'teams_rang_list#index'
  get 'teams_rang_list_4_1', to: 'teams_rang_list#index4plus1'

  resources :team_badges

  resources :team_players

  resources :player_badges

  get 'own_goals/index'
  get 'own_goals/show'
  get 'own_goals/update'

  get 'comments/index'
  get 'comments/show'
  get 'comments/update'

  resources :calendar

  get "welcome/index"
  root :to => 'welcome#index'

  resources :welcome_pages
  get 'kontakt', to: 'welcome_pages#contact'

  resources :tournaments
  
  resources :rules
  get 'rules51', to: 'rules#rules51'
  get 'rules41', to: 'rules#rules41'
  get 'izvod', to: 'rules#izvod'

  resources :users, except: [:new, :create]

  resources :admins
  get 'registruj_admina', to: 'admins#new'

  resources :players

  get 'registruj_ekipu', to: 'teams#new'
  resources :teams
  get 'new_ten_players', to: 'teams#new_ten_players', via: :post
  get 'new_twelve_players', to: 'teams#new_twelve_players', via: :post
  get 'new_fourteen_players', to: 'teams#new_fourteen_players', via: :post
  get 'new_sixteen_players', to: 'teams#new_sixteen_players', via: :post

  get 'registruj_delegata', to: 'delegates#new'
  resources :delegates

  resources :articles
  
  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  
  ############################################
  # Ova komanda je za sistem za razmenu poruka 
  ############################################

  # before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  #######################################################
  # @mailbox je definisan u private, metodom :get_mailbox
  #######################################################

  def index
    if @box.eql? "primljene poruke"
      @conversations = @mailbox.inbox
    elsif @box.eql? "poslate poruke"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  #################################################################
  # @conversation je definisan u private, metodom :get_conversation
  #################################################################

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply poslate poruke'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  #############################################
  # PRIVATE
  #############################################
  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !["primljene poruke","poslate poruke","trash"].include?(params[:box])
      params[:box] = 'primljene poruke'
    end
    @box = params[:box]
  end
end

app/helpers/conversation_helper.rb
############################################
# Ova komanda je za sistem za razmenu poruka 
############################################

module ConversationHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<!--Ovo je HTML za sistem za razmenu poruka-->



   <tr> 
      <td > <%= render 'conversations/participants', conversation:   conversation %></td>
      
      <td >
         <%= link_to conversation.subject[0..20], conversation_path(conversation)%></td>
      
      <td><%= conversation.last_message.body %></td>
      <td> <small><span class="text-muted"><%= conversation.last_message.created_at.strftime"( %-d %B %Y, %H:%M:%S )" %></span></small></td>
      
      <td><div class="btn-group-vertical pull-right">
            <% if conversation.is_trashed?(current_user) %>
                <%= link_to @language_2.restore, restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
            <% else %>
                <%= link_to @language_2.kanta, conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                    data: {confirm: '#{@language_2.are_you_sure}'} %>
         
                <% if conversation.is_unread?(current_user) %>
                      <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                      class: 'btn btn-xs btn-info', method: :post %>
                <% end %>
            <% end %>
                  
          </div>
              
      </td>
      
    </tr>

app/views/conversations/_participants.html.erb
<!--Ovo je HTML za sistem za razmenu poruka-->

<% conversation.participants.each do |participant| %>
  	<% unless participant == current_user %>
   		<% if participant.player %>
    		<%= "#{participant.player[:name]} #{participant.player[:surname]}"  %>
		<% elsif participant.delegate %>
			<%= "#{participant.delegate[:name]} #{participant.delegate[:surname]}" %>
		<% elsif participant.admin %>
			<%= "#{participant.admin[:name]} #{participant.admin[:surname]}" %>
		<% end %>
  	<% end %>
<% end %>

app/views/conversations/index.html.erb
<!--Ovo je HTML za sistem za razmenu poruka-->
<div id='wrapper'>
    <h1>Poruke</h1>
</div>

<div class="OnlyforWeb">
  <div class="row">
    <div class="col-sm-3">
      <ul class="nav nav-pills nav-stacked">
        <%= link_to @language_2.posalji_poruku, new_message_path, class: 'startconv'%>
        <%= mailbox_section @language_2.primljene_poruke, @box %>
        <%= mailbox_section @language_2.poslate_poruke, @box %>
        <%= mailbox_section @language_2.kanta, @box %>
      </ul>
    </div>

    <div class="col-sm-9">
      <% if @box == @language_2.kanta %>
        <p><%= link_to @language_2.isprazni_kantu, empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
                         data: {confirm: '#{@language_2.are_you_sure}'} %></p>
      <% end %>

      <table class="list-group">
          <tr>
              <th>  <%= @language_2.ime_i_prezime %></th>
              <th>  <%= @language_2.naslov %> </th>
              <th>  <%= @language_2.poruka %> </th>
              <th>  <%= @language.datum %> </th>
              <th></th>
          </tr>
          <%= render partial: 'conversations/conversation', collection: @conversations %>
      </table>

      <%= will_paginate %>
    </div>
  </div>
</div>

<div class="OnlyforHandheld">
    <div class="">
      <ul class="nav nav-pills nav-stacked">
        <%= link_to @language_2.posalji_poruku, new_message_path, class: 'startconv'%>
        <%= mailbox_section @language_2.primljene_poruke, @box %>
        <%= mailbox_section @language_2.poslate_poruke, @box %>
        <%= mailbox_section @language_2.kanta, @box %>
      </ul>
    </div>

    <div class="col-sm-9">
      <% if @box == 'trash' %>
        <p><%= link_to @language_2.isprazni_kantu, empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
                       data: {confirm: '#{@language_2.are_you_sure}'} %></p>
      <% end %>

      <table class="list-group">
          <tr>
              <th>  <%= @language_2.ime_i_prezime %> </th>
              <th>  <%= @language_2.naslov %> </th>
              <th>  <%= @language_2.poruka %> </th>
              <th>  <%= @language.datum %> </th>
              <th></th>
          </tr>
          <%= render partial: 'conversations/conversation', collection: @conversations %>
      </table>

      <%= will_paginate %>
    </div>
</div>

app/views/conversations/show.html.erb
<!--Ovo je HTML za sistem za razmenu poruka-->
<div id='wrapper'>
    <h1><%= @language_2.prepiska_sa %>
  <%= render 'conversations/participants', conversation: @conversation %>
</h1>

</div>
<div class="conversation-container">

  <div class="panel panel-default">
    <div class="panel-heading"><%= @conversation.subject[0..20] %></div>

    <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>
          <div class="media-left">
            <%= message.sender.username %>
          </div>

          <div class="media-body">
            <h4><%= message.body %></h4>
            <h6><%= message.sender.username %></h6>
              <small><span class="text-muted"> poslato <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span></small>
            
          </div>
        </div>
      <% end %>
     </div>
    </div>
  </div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: "#{@language_2.ukucaj_poruku}", required: true %>
  
  
  <%= submit_tag @language_2.posalji, class: 'send_button' %>
<% end %>
</div>
</div>