config/routes.rb
Rails.application.routes.draw do

 

  devise_for :users, :controllers => {sessions: 'user/sessions', registrations: 'user/registrations', passwords: 'user/passwords' } 

  namespace :api do
    namespace :v1 do
      resources :articles, :defaults => { :format => 'json' }
      resources :players, :defaults => { :format => 'json' } # xml
      resources :player_seasons, :defaults => { :format => 'json' }
      resources :player_badges, :defaults => { :format => 'json' }
      resources :teams, :defaults => { :format => 'json' } # xml
      resources :team_seasons, :defaults => { :format => 'json' }
      resources :home_teams, :defaults => { :format => 'json' }
      resources :away_teams, :defaults => { :format => 'json' }
      resources :team_badges, :defaults => { :format => 'json' }
      resources :delegates, :defaults => { :format => 'json' }
      resources :matches, :defaults => { :format => 'json' }
      resources :goals, :defaults => { :format => 'json' }
      resources :assists, :defaults => { :format => 'json' }
      resources :fouls, :defaults => { :format => 'json' }
      resources :yellow_cards, :defaults => { :format => 'json' }
      resources :red_cards, :defaults => { :format => 'json' }
      resources :goalkeeper_saves, :defaults => { :format => 'json' }
      resources :shoots, :defaults => { :format => 'json' }
      post 'new_home_shoot', to: 'shoots#new_home', :defaults => { :format => 'json' }
      post 'new_away_shoot', to: 'shoots#new_away', :defaults => { :format => 'json' }
      put 'change_match_started', to: 'matches#change_match_started', :defaults => { :format => 'json' }
      patch 'change_match_started', to: 'matches#change_match_started', :defaults => { :format => 'json' }
      put 'change_first_half_ended', to: 'matches#change_first_half_ended', :defaults => { :format => 'json' }
      patch 'change_first_half_ended', to: 'matches#change_first_half_ended', :defaults => { :format => 'json' }
      put 'change_second_half_started', to: 'matches#change_second_half_started', :defaults => { :format => 'json' }
      patch 'change_second_half_started', to: 'matches#change_second_half_started', :defaults => { :format => 'json' }
      put 'change_second_half_ended', to: 'matches#change_second_half_ended', :defaults => { :format => 'json' }
      patch 'change_second_half_ended', to: 'matches#change_second_half_ended', :defaults => { :format => 'json' }
      resources :match_players, :defaults => { :format => 'json' }
      post 'chooseplayers', to: 'match_players#chooseplayers', :defaults => { :format => 'json' }
      resources :players_rang_list, :defaults => { :format => 'json' }
      get 'players_rang_list', to: 'players_rang_list#index', :defaults => { :format => 'json'}
      get 'players_rang_list_4_1', to: 'players_rang_list#index4plus1', :defaults => { :format => 'json'}
      resources :teams_rang_list, :defaults => { :format => 'json' }
      get 'teams_rang_list', to: 'teams_rang_list#index', :defaults => { :format => 'json' }
      get 'teams_rang_list_4_1', to: 'teams_rang_list#index4plus1', :defaults => { :format => 'json' }
      resources :leagues, :defaults => { :format => 'json' }
    end   
  end

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'

  mount Commontator::Engine => '/commontator'
  
   resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]
  get 'messages/new'

  resources :contactmessages, only: [:new, :create]
  

  resources :home_teams

  resources :away_teams

  resources :stadions

  resources :referees

  resources :livescores

  resources :matches do
    member do
      put 'change_match_started', to: 'matches#change_match_started'
      patch 'change_match_started', to: 'matches#change_match_started'

      put 'change_first_half_ended', to: 'matches#change_first_half_ended'
      patch 'change_first_half_ended', to: 'matches#change_first_half_ended'

      put 'change_second_half_started', to: 'matches#change_second_half_started'
      patch 'change_second_half_started', to: 'matches#change_second_half_started'

      put 'change_second_half_ended', to: 'matches#change_second_half_ended'
      patch 'change_second_half_ended', to: 'matches#change_second_half_ended'
    end
  end

  resources :leagues
  
  get 'four_plus_one_leagues', to: 'leagues#fourplusone'
  get 'five_plus_one_leagues', to: 'leagues#fiveplusone'
  resources :team_seasons

  resources :player_seasons

  resources :stats

  resources :results

  resources :seasons

  get 'new_home_players', to: 'match_players#new_home', via: :post
  get 'new_away_players', to: 'match_players#new_away', via: :post
  post 'chooseplayers', to: 'match_players#chooseplayers'

  resources :goals
  get 'new_home_goal', to: 'goals#new_home', via: :post
  get 'new_away_goal', to: 'goals#new_away', via: :post

  resources :assists
  get 'new_home_assist', to: 'assists#new_home', via: :post
  get 'new_away_assist', to: 'assists#new_away', via: :post

  resources :fouls
  get 'new_home_foul', to: 'fouls#new_home', via: :post
  get 'new_away_foul', to: 'fouls#new_away', via: :post

  resources :yellow_cards
  get 'new_home_yellow_card', to: 'yellow_cards#new_home', via: :post
  get 'new_away_yellow_card', to: 'yellow_cards#new_away', via: :post

  resources :red_cards
  get 'new_home_red_card', to: 'red_cards#new_home', via: :post
  get 'new_away_red_card', to: 'red_cards#new_away', via: :post

  resources :shoots
  get 'new_home_shoot', to: 'shoots#new_home', via: :post
  get 'new_away_shoot', to: 'shoots#new_away', via: :post

  resources :goalkeeper_saves
  get 'new_home_goalkeeper_save', to: 'goalkeeper_saves#new_home', via: :post
  get 'new_away_goalkeeper_save', to: 'goalkeeper_saves#new_away', via: :post

  get 'league_seasons/index'
  get 'league_seasons/new'
  get 'league_seasons/create'
  get 'league_seasons/edit'
  get 'league_seasons/update'
  get 'league_seasons/show'

  resources :league_pages

  resources :goalkeeper_saves
  get 'new_home_goalkeeper_save', to: 'goalkeeper_saves#new_home', via: :post
  get 'new_away_goalkeeper_save', to: 'goalkeeper_saves#new_away', via: :post

  get 'rankings/index'
  get 'rankings/show'
  get 'rankings/update'
  get 'rankings/teams'
  get 'rankings/players'

  get 'players_rang_list', to: 'players_rang_list#index'
  get 'players_rang_list_4_1', to: 'players_rang_list#index4plus1'

  get 'teams_rang_list', to: 'teams_rang_list#index'
  get 'teams_rang_list_4_1', to: 'teams_rang_list#index4plus1'

  resources :team_badges

  resources :team_players

  resources :player_badges

  get 'own_goals/index'
  get 'own_goals/show'
  get 'own_goals/update'

  get 'comments/index'
  get 'comments/show'
  get 'comments/update'

  resources :calendar

  get "welcome/index"
  root :to => 'welcome#index'

  resources :welcome_pages
  get 'kontakt', to: 'welcome_pages#contact'

  resources :tournaments
  
  resources :rules
  get 'rules51', to: 'rules#rules51'
  get 'rules41', to: 'rules#rules41'
  get 'izvod', to: 'rules#izvod'

  resources :users, except: [:new, :create]

  resources :admins
  get 'registruj_admina', to: 'admins#new'

  resources :players

  get 'registruj_ekipu', to: 'teams#new'
  resources :teams
  get 'new_ten_players', to: 'teams#new_ten_players', via: :post
  get 'new_twelve_players', to: 'teams#new_twelve_players', via: :post
  get 'new_fourteen_players', to: 'teams#new_fourteen_players', via: :post
  get 'new_sixteen_players', to: 'teams#new_sixteen_players', via: :post

  get 'registruj_delegata', to: 'delegates#new'
  resources :delegates

  resources :articles
  
  
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
  end

  # Tabela MATCHES PER LEAGUE
  def show
    # Nije isprobano!
    @league = League.find(params[:id])
    @matches = Match.where(:league_id => @league.id, :is_match_started => 1, :is_match_finished => 1, :season_id => Season.last.id)
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_match.html.erb
<% obj.each do |match| %>
	<tr onclick='location.href="<%= match_path(match) %>"' class="OnlyforWeb">
		<% if match.match_date != nil %>
			<td><%= match.match_date.strftime("%d. %m. %y") %></td>
			<td><%= match.match_date.strftime("%H:%M") %></td>
		<% else %>
			<td></td>
			<td></td>
		<% end %>
		<% if match.home_team != nil %>
			<% if match.home_team.team != nil %>
				<td><%= link_to match.home_team.team.name, team_path(match.home_team.team) %></td>
				<td><%= image_tag match.home_team.team.avatar.url(:logo), height: "40px" %></td> <!-- Slika ekipe -->
			<% else %>
				<td></td>
				<td></td>
			<% end %>
		<% end %>
		<td style="min-width:117px;"><h2><%= "#{match.home_goals} - #{match.away_goals}" %></h2></td>
		<% if match.away_team != nil %>
			<% if match.away_team.team != nil %>
				<td><%= image_tag match.away_team.team.avatar.url(:logo), height: "40px" %></td> <!-- Slika ekipe -->
				<td><%= link_to match.away_team.team.name, team_path(match.away_team.team) %></td>
			<% else %>
				<td></td>
				<td></td>
			<% end %>
		<% end %>
		<% if match.league != nil %>
			<td><%= link_to match.league.name, league_page_path(match.league) %></td>
		<% else %>
			<td></td>
		<% end %>
		<% if match.away_team != nil %>
			<% if match.away_team.team != nil %>
				<td><%= link_to match.season.name, match_path(match) %></td>
			<% else %>
				<td></td>
			<% end %>
		<% end %>
		<% if match.stadion != nil %>
			<td><%= match.stadion.name %></td>
		<% else %>
			<td></td>
		<% end %>
	</tr>
	<tr onclick='location.href="<%= match_path(match) %>"' class="OnlyforHandheld">
		<% if match.match_date != nil %>
			<td><%= match.match_date.strftime("%d. %m. %y") %><br><%= match.match_date.strftime("%H:%M") %></td>
		<% end %>

		<% if match.home_team != nil %>
			<% if match.home_team.team != nil %>
				<td><%= image_tag match.home_team.team.avatar.url(:logo), height: "40px" %><br>
				<%= link_to match.home_team.team.name, team_path(match.home_team.team) %></td>
			<% else %>
				<td></td>
			<% end %>
		<% end %>
		
		<td style="min-width:90px;"><h2 style="font-size: 18px;"><%= "#{match.home_goals} - #{match.away_goals}" %></h2></td>
		
		<% if match.home_team != nil %>
			<% if match.home_team.team != nil %>
				<td><%= image_tag match.away_team.team.avatar.url(:logo), height: "40px" %><br>
				<%= link_to match.away_team.team.name, team_path(match.away_team.team) %></td>
			<% else %>
				<td></td>
			<% end %>
		<% end %>
		
	</tr>
<% end %>

app/views/results/index.html.erb
<h1>Results#index</h1>
<p>Find me in app/views/results/index.html.erb</p>

app/views/results/show.html.erb
<head>
  <title><%= @language_2.unesi_naziv_sezone %>|<%= @organisation_info.organisation_name %></title>
</head>
<body>
	<div id='wrapper'>
		<h1><%= @language_2.unesi_naziv_sezone %></h1>
	</div>
	<div class="center results-font">
		<div class="OnlyforWeb">
			 <div class="player-stats-padding">
				<table class="player-stats">
				<tr>
					<th><%= @language.datum %></th>
					<th><%= @language.vreme %></th>
					<th><%= @language.domacin %></th>
					<th></th>
					<th><%= @language.rezultat %></th>
					<th></th>
					<th><%= @language.gost %></th>
					<th><%= @language.liga %></th>
					<th><%= @language.sezona %></th>
					<th><%= @language_2.teren %></th>
				</tr>
				<%= render 'results/match', obj: @matches.sort_by{|e| e[:match_date]}.reverse %>
				</table>
			</div>
		</div>
		<div class="OnlyforHandheld">
			 <div class="player-stats-padding">
				<table class="player-stats-match-results">
				<tr>
					<th style="min-width:80px; font-size: 14px;"><%= @language.datum %><br><%= @language.vreme %></th>
					<th style="font-size: 14px"><%= @language.domacin %></th>
					<th style="font-size: 14px"><%= @language.rezultat %></th>
					<th style="font-size: 14px"><%= @language.gost %></th>
				</tr>
				<%= render 'results/match', obj: @matches.sort_by{|e| e[:match_date]}.reverse %>
				</table>
			</div>
		</div>	
	</div>
</body>