config/routes.rb
Rails.application.routes.draw do

 

  devise_for :users, :controllers => {sessions: 'user/sessions', registrations: 'user/registrations', passwords: 'user/passwords' } 

  namespace :api do
    namespace :v1 do
      resources :articles, :defaults => { :format => 'json' }
      resources :players, :defaults => { :format => 'json' } # xml
      resources :player_seasons, :defaults => { :format => 'json' }
      resources :player_badges, :defaults => { :format => 'json' }
      resources :teams, :defaults => { :format => 'json' } # xml
      resources :team_seasons, :defaults => { :format => 'json' }
      resources :home_teams, :defaults => { :format => 'json' }
      resources :away_teams, :defaults => { :format => 'json' }
      resources :team_badges, :defaults => { :format => 'json' }
      resources :delegates, :defaults => { :format => 'json' }
      resources :matches, :defaults => { :format => 'json' }
      resources :goals, :defaults => { :format => 'json' }
      resources :assists, :defaults => { :format => 'json' }
      resources :fouls, :defaults => { :format => 'json' }
      resources :yellow_cards, :defaults => { :format => 'json' }
      resources :red_cards, :defaults => { :format => 'json' }
      resources :goalkeeper_saves, :defaults => { :format => 'json' }
      resources :shoots, :defaults => { :format => 'json' }
      post 'new_home_shoot', to: 'shoots#new_home', :defaults => { :format => 'json' }
      post 'new_away_shoot', to: 'shoots#new_away', :defaults => { :format => 'json' }
      put 'change_match_started', to: 'matches#change_match_started', :defaults => { :format => 'json' }
      patch 'change_match_started', to: 'matches#change_match_started', :defaults => { :format => 'json' }
      put 'change_first_half_ended', to: 'matches#change_first_half_ended', :defaults => { :format => 'json' }
      patch 'change_first_half_ended', to: 'matches#change_first_half_ended', :defaults => { :format => 'json' }
      put 'change_second_half_started', to: 'matches#change_second_half_started', :defaults => { :format => 'json' }
      patch 'change_second_half_started', to: 'matches#change_second_half_started', :defaults => { :format => 'json' }
      put 'change_second_half_ended', to: 'matches#change_second_half_ended', :defaults => { :format => 'json' }
      patch 'change_second_half_ended', to: 'matches#change_second_half_ended', :defaults => { :format => 'json' }
      resources :match_players, :defaults => { :format => 'json' }
      post 'chooseplayers', to: 'match_players#chooseplayers', :defaults => { :format => 'json' }
      resources :players_rang_list, :defaults => { :format => 'json' }
      get 'players_rang_list', to: 'players_rang_list#index', :defaults => { :format => 'json'}
      get 'players_rang_list_4_1', to: 'players_rang_list#index4plus1', :defaults => { :format => 'json'}
      resources :teams_rang_list, :defaults => { :format => 'json' }
      get 'teams_rang_list', to: 'teams_rang_list#index', :defaults => { :format => 'json' }
      get 'teams_rang_list_4_1', to: 'teams_rang_list#index4plus1', :defaults => { :format => 'json' }
      resources :leagues, :defaults => { :format => 'json' }
    end   
  end

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'

  mount Commontator::Engine => '/commontator'
  
   resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]
  get 'messages/new'

  resources :contactmessages, only: [:new, :create]
  

  resources :home_teams

  resources :away_teams

  resources :stadions

  resources :referees

  resources :livescores

  resources :matches do
    member do
      put 'change_match_started', to: 'matches#change_match_started'
      patch 'change_match_started', to: 'matches#change_match_started'

      put 'change_first_half_ended', to: 'matches#change_first_half_ended'
      patch 'change_first_half_ended', to: 'matches#change_first_half_ended'

      put 'change_second_half_started', to: 'matches#change_second_half_started'
      patch 'change_second_half_started', to: 'matches#change_second_half_started'

      put 'change_second_half_ended', to: 'matches#change_second_half_ended'
      patch 'change_second_half_ended', to: 'matches#change_second_half_ended'
    end
  end

  resources :leagues
  
  get 'four_plus_one_leagues', to: 'leagues#fourplusone'
  get 'five_plus_one_leagues', to: 'leagues#fiveplusone'
  resources :team_seasons

  resources :player_seasons

  resources :stats

  resources :results

  resources :seasons

  get 'new_home_players', to: 'match_players#new_home', via: :post
  get 'new_away_players', to: 'match_players#new_away', via: :post
  post 'chooseplayers', to: 'match_players#chooseplayers'

  resources :goals
  get 'new_home_goal', to: 'goals#new_home', via: :post
  get 'new_away_goal', to: 'goals#new_away', via: :post

  resources :assists
  get 'new_home_assist', to: 'assists#new_home', via: :post
  get 'new_away_assist', to: 'assists#new_away', via: :post

  resources :fouls
  get 'new_home_foul', to: 'fouls#new_home', via: :post
  get 'new_away_foul', to: 'fouls#new_away', via: :post

  resources :yellow_cards
  get 'new_home_yellow_card', to: 'yellow_cards#new_home', via: :post
  get 'new_away_yellow_card', to: 'yellow_cards#new_away', via: :post

  resources :red_cards
  get 'new_home_red_card', to: 'red_cards#new_home', via: :post
  get 'new_away_red_card', to: 'red_cards#new_away', via: :post

  resources :shoots
  get 'new_home_shoot', to: 'shoots#new_home', via: :post
  get 'new_away_shoot', to: 'shoots#new_away', via: :post

  resources :goalkeeper_saves
  get 'new_home_goalkeeper_save', to: 'goalkeeper_saves#new_home', via: :post
  get 'new_away_goalkeeper_save', to: 'goalkeeper_saves#new_away', via: :post

  get 'league_seasons/index'
  get 'league_seasons/new'
  get 'league_seasons/create'
  get 'league_seasons/edit'
  get 'league_seasons/update'
  get 'league_seasons/show'

  resources :league_pages

  resources :goalkeeper_saves
  get 'new_home_goalkeeper_save', to: 'goalkeeper_saves#new_home', via: :post
  get 'new_away_goalkeeper_save', to: 'goalkeeper_saves#new_away', via: :post

  get 'rankings/index'
  get 'rankings/show'
  get 'rankings/update'
  get 'rankings/teams'
  get 'rankings/players'

  get 'players_rang_list', to: 'players_rang_list#index'
  get 'players_rang_list_4_1', to: 'players_rang_list#index4plus1'

  get 'teams_rang_list', to: 'teams_rang_list#index'
  get 'teams_rang_list_4_1', to: 'teams_rang_list#index4plus1'

  resources :team_badges

  resources :team_players

  resources :player_badges

  get 'own_goals/index'
  get 'own_goals/show'
  get 'own_goals/update'

  get 'comments/index'
  get 'comments/show'
  get 'comments/update'

  resources :calendar

  get "welcome/index"
  root :to => 'welcome#index'

  resources :welcome_pages
  get 'kontakt', to: 'welcome_pages#contact'

  resources :tournaments
  
  resources :rules
  get 'rules51', to: 'rules#rules51'
  get 'rules41', to: 'rules#rules41'
  get 'izvod', to: 'rules#izvod'

  resources :users, except: [:new, :create]

  resources :admins
  get 'registruj_admina', to: 'admins#new'

  resources :players

  get 'registruj_ekipu', to: 'teams#new'
  resources :teams
  get 'new_ten_players', to: 'teams#new_ten_players', via: :post
  get 'new_twelve_players', to: 'teams#new_twelve_players', via: :post
  get 'new_fourteen_players', to: 'teams#new_fourteen_players', via: :post
  get 'new_sixteen_players', to: 'teams#new_sixteen_players', via: :post

  get 'registruj_delegata', to: 'delegates#new'
  resources :delegates

  resources :articles
  
  
end

app/controllers/api/v1/matches_controller.rb
class Api::V1::MatchesController < ApplicationController
  before_action :set_match, only:[:edit, 
                                  :update, 
                                 :show, 
                                  :change_match_started,
                                  :change_first_half_ended,
                                  :change_second_half_started,
                                  :change_second_half_ended]
  skip_before_filter :authenticate_user! # we do not need devise authentication here
  skip_before_action :verify_authenticity_token

  def index
    @matches = Match.all
    respond_to do |format|
      format.json { render json: @matches }
      format.xml { render xml: @matches }
    end
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
    respond_to do |format|
      format.json { render json: @match }
      format.xml { render xml: @match }
    end

    if logged_in?
      if current_user.delegate #&& !@match.is_match_finished
        # Ovde sesija treba automatski da se napravi
        # kada delegat poseti stranica
        if session[:match_id] != @match.id
          session[:match_id] = @match.id
        end
      end
    end

    if @match != nil
      @pauza = (@match.second_half_started - @match.first_half_ended)
      @minut_utakmice = (DateTime.now.seconds_since_midnight - @pauza - @match.match_started).to_f / 60
      @minut_utakmice = @minut_utakmice.round + 1
    end

    ######################################
    # Definisan home team
    ######################################
    @home_team = @match.home_team.team
    @home_team_season = @home_team.team_season

    ######################################
    # Definisan away team
    ######################################
    @away_team = @match.away_team.team
    @away_team_season = @away_team.team_season

    ######################################
    # HOME TEAM PLAYER SEASONS ON MATCH
    ######################################
    # U promenljivu home_match_players postavljamo igrace
    # koji su izabrani da su dosli na utakmicu
    @home_match_players = MatchPlayer.where(
      :match_id => @match.id,
      :is_home => 1)

    # Ovde trazimo home_player_sezone za izabrane igrace,
    # glavna promenljiva je home_player_seasons_on_match
    i = 0
    @home_match_players.each do |home_match_player|
      @home_player_season_on_match = PlayerSeason.where(:id => home_match_player.player_season_id)
      if i == 0 then
        @home_player_seasons_on_match = @home_player_season_on_match
      else
        # HOME PLAYER_SEASONS ON MATCH
        @home_player_seasons_on_match.concat(@home_player_season_on_match)
      end
      i = 1
    end

    ######################################
    # AWAY TEAM PLAYER SEASONS ON MATCH
    ######################################
    # U promenljivu away_match_players postavljamo igrace
    # koji su izabrani da su dosli na utakmicu
    @away_match_players = MatchPlayer.where(
      :match_id => @match.id,
      :is_home => 0)

    # Ovde trazimo home_player_sezone za izabrane igrace,
    # glavna promenljiva je home_player_seasons_on_match
    i = 0
    @away_match_players.each do |away_match_player|
      @away_player_season_on_match = PlayerSeason.where(:id => away_match_player.player_season_id)
      if i == 0 then
        @away_player_seasons_on_match = @away_player_season_on_match
      else
        # AWAY PLAYER_SEASONS ON MATCH
        @away_player_seasons_on_match.concat(@away_player_season_on_match)
      end
      i = 1
    end

    @home_goals_on_match = Goal.where(:is_home => 1, :match_id => @match.id)
    @away_goals_on_match = Goal.where(:is_home => 0, :match_id => @match.id)  
  end

  def change_match_started
    # Metod .seconds_since_midnight vraca integer koliko sekundi je proslo od ponoci
    # tako mozemo da izracunamo u kojoj sekundi je postignut gol itd.
    #@match = Match.update(params)
    @match.update(:match_started => DateTime.now.seconds_since_midnight, :is_match_started => true)
    # Ranije se ovde sesija otvarala, sada u metodu show ovog kontrolera
    respond_to do |format|
      format.json { render json: @match }
      format.xml { render xml: @match }
    end
  end

  def change_first_half_ended
    respond_to do |format|
      format.json { render json: @match }
      format.xml { render xml: @match }
    end
    # Metod .seconds_since_midnight vraca integer koliko sekundi je proslo od ponoci
    # tako mozemo da izracunamo u kojoj sekundi je postignut gol itd.
    @match.update(:first_half_ended => DateTime.now.seconds_since_midnight)

    # OVDE LOGIKA O REZULTATU NA POLUVREMENU, UPDATE POBEDA,
    # IZGUBLJENIH, NERESENIH...
    # I ZA IGRACA I ZA TIM

  end

  def change_second_half_started
    respond_to do |format|
      format.json { render json: @match }
      format.xml { render xml: @match }
    end
    # Metod .seconds_since_midnight vraca integer koliko sekundi je proslo od ponoci
    # tako mozemo da izracunamo u kojoj sekundi je postignut gol itd.
    @match.update(:second_half_started => DateTime.now.seconds_since_midnight)
  end

  # LOGIKA kada se mec zavrsi
  def change_second_half_ended
    respond_to do |format|
      format.json { render json: @match }
      format.xml { render xml: @match }
    end
    # Metod .seconds_since_midnight vraca integer koliko sekundi je proslo od ponoci
    # tako mozemo da izracunamo u kojoj sekundi je postignut gol itd.
    @match.update(:match_finished => DateTime.now.seconds_since_midnight)


    ########################
    # Definicije za EXP
    ########################
    ########################
    # Vaznost utakmice
    ########################
    # 1) prijateljski mec, V = 1
    if @match.is_friendly
      @v = 1
    # 2) drugoligaski mec, V = 2.5
    elsif @match.is_second_league
      @v = 2.5
    # 3) kup, V = 3.0
    elsif @match.is_tournament
      @v = 3.0
    # 4) prvoligaski mec, V = 4.0
    elsif @match.is_first_league
      @v = 4.0
    end
 
    ###########################
    # Jacina protivnickog tima
    ###########################
    # Definisan home team
    @home_team = @match.home_team.team
    @home_team_season = @home_team.team_season
    # Definisan away team
    @away_team = @match.away_team.team
    @away_team_season = @away_team.team_season
    #############################
    # Racunamo jacinu HOME tima
    #############################
    # Za prvoplasiranu i poslednjih 15 ekipa postoje drugi kriterijumi za bodovanje
    # LIGA 4+1
    if @home_team.league.is_fourplusone
      if @home_team.team_season.position == nil || @home_team.team_season.position == 0
        @home_team.team_season.position = 0
        @jacina_domaceg_tima = 15
      # Ako je protivnicki tim prvoplasiran dobija maksimalan broj bodova
      elsif @home_team.team_season.position == 1
        @jacina_domaceg_tima = 64
      # Standardna formula za racunanje bodova
      elsif @home_team.team_season.position > 1 && @home_team.team_season.position < 50
        @jacina_domaceg_tima = 64 - @home_team.team_season.position
      # Ako je protivnicki tim u poslednjih petnaest
      elsif @home_team.team_season.position > 49
        @jacina_domaceg_tima = 15
      end
    # LIGA 5+1
    elsif @home_team.league.is_fiveplusone
      if @home_team.team_season.position == nil || @home_team.team_season.position == 0
        @home_team.team_season.position = 0
        @jacina_domaceg_tima = 15
      # Ako je protivnicki tim prvoplasiran dobija maksimalan broj bodova
      elsif @home_team.team_season.position == 1
        @jacina_domaceg_tima = 80
      # Standardna formula za racunanje bodova
      elsif @home_team.team_season.position > 1 && @home_team.team_season.position < 66
        @jacina_domaceg_tima = 80 - @home_team.team_season.position
      # Ako je protivnicki tim u poslednjih petnaest
      elsif @home_team.team_season.position > 65
        @jacina_domaceg_tima = 15
      end
    end
    @j_home = @jacina_domaceg_tima

    #############################
    # Racunamo jacinu AWAY tima
    #############################
        # Za prvoplasiranu i poslednjih 15 ekipa postoje drugi kriterijumi za bodovanje
    # LIGA 4+1
    if @away_team.league.is_fourplusone
      if @away_team.team_season.position == nil || @away_team.team_season.position == 0
        @away_team.team_season.position = 0
        @jacina_gostujuceg_tima = 15
      # Ako je protivnicki tim prvoplasiran dobija maksimalan broj bodova
      elsif @away_team.team_season.position == 1
        @jacina_gostujuceg_tima = 64
      # Standardna formula za racunanje bodova
      elsif @away_team.team_season.position > 1 && @away_team.team_season.position < 50
        @jacina_gostujuceg_tima = 64 - @away_team.team_season.position
      # Ako je protivnicki tim u poslednjih petnaest
      elsif @away_team.team_season.position > 49
        @jacina_gostujuceg_tima = 15
      end
    # LIGA 5+1
    elsif @away_team.league.is_fiveplusone
      if @away_team.team_season.position == nil  || @away_team.team_season.position == 0
        @away_team.team_season.position = 0
        @jacina_gostujuceg_tima = 15
      # Ako je protivnicki tim prvoplasiran dobija maksimalan broj bodova
      elsif @away_team.team_season.position == 1
        @jacina_gostujuceg_tima = 80
      # Standardna formula za racunanje bodova
      elsif @away_team.team_season.position > 1 && @away_team.team_season.position < 66
        @jacina_gostujuceg_tima = 80 - @away_team.team_season.position
      # Ako je protivnicki tim u poslednjih petnaest
      elsif @away_team.team_season.position > 65
        @jacina_gostujuceg_tima = 15
      end
    end
    @j_away = @jacina_gostujuceg_tima


    ###########################################################
    ###########################################################

    ########################
    # HOME TEAM
    ########################
    

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_away_goal_score.html.erb
<table>
	<% obj.in_groups_of(3, false) do |home_goals| %>
		<tr>
			<% for home_goal in home_goals %>
				<td style="color:white; font-size: 17px;"><%= image_tag("emoticons/soccerball.png", :alt => "gol", height:"20px") %><%= " #{home_goal.player_season.player.name} #{home_goal.player_season.player.surname} '#{home_goal.created_at}" %>&nbsp;&nbsp;</td>
			<% end %>
		</tr>
	<% end %>
</table>

app/views/matches/_away_players.html.erb
<% if @match.is_match_finished && (@home_player_seasons_on_match != nil && @away_player_seasons_on_match != nil) %>
	<!-- Nalazenje @max, koji predstavlja veci broj od broja igraca koji su dosli iz jednog i drugog tima -->
	<% if @home_player_seasons_on_match.size >= @away_player_seasons_on_match.size %>
		<% @max = @home_player_seasons_on_match.size %>
	<% elsif @home_player_seasons_on_match.size < @away_player_seasons_on_match.size %>
		<% @max = @away_player_seasons_on_match.size %>	
	<% end %>

	<!-- Stampanje igraca koji su dosli na utakmicu -->
	<% for @obj in 0..@max %>
		<% unless (@home_player_seasons_on_match[@obj] == nil) && (@away_player_seasons_on_match[@obj] == nil) %>
				<% if @away_player_seasons_on_match[@obj] != nil %>	
				<tr>			
					<td><%= link_to "#{@away_player_seasons_on_match[@obj].player.name}", player_path(@away_player_seasons_on_match[@obj].player) %> <%= link_to "#{@away_player_seasons_on_match[@obj].player.surname}", player_path(@away_player_seasons_on_match[@obj].player) %></td>
					<td style="max-width: 30px"><%= Goal.where(:player_season_id => @away_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj golova tog igraca na ovoj utakmici -->
					<td style="max-width: 30px"><%= Assist.where(:player_season_id => @away_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj asistencija tog igraca na ovoj utakmici -->
					<td style="max-width: 30px"><%= YellowCard.where(:player_season_id => @away_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj golova tog igraca na ovoj utakmici -->
					<td style="max-width: 30px"><%= RedCard.where(:player_season_id => @away_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj golova tog igraca na ovoj utakmici -->
				</tr>
				<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/matches/_home_goal_score.html.erb
<table>
	<% obj.in_groups_of(3, false) do |home_goals| %>
		<tr>
			<% for home_goal in home_goals %>
				<td style="color:white; font-size: 17px;"><%= image_tag("emoticons/soccerball.png", :alt => "gol", height:"20px") %><%= " #{home_goal.player_season.player.name} #{home_goal.player_season.player.surname} '#{home_goal.created_at}" %>&nbsp;&nbsp;</td>
			<% end %>
		</tr>
	<% end %>
</table>

app/views/matches/_home_players.html.erb
<% if @match.is_match_finished && (@home_player_seasons_on_match != nil && @away_player_seasons_on_match != nil) %>
	<!-- Nalazenje @max, koji predstavlja veci broj od broja igraca koji su dosli iz jednog i drugog tima -->
	<% if @home_player_seasons_on_match.size >= @away_player_seasons_on_match.size %>
		<% @max = @home_player_seasons_on_match.size %>
	<% elsif @home_player_seasons_on_match.size < @away_player_seasons_on_match.size %>
		<% @max = @away_player_seasons_on_match.size %>	
	<% end %>

	<!-- Stampanje igraca koji su dosli na utakmicu -->
	<% for @obj in 0..@max %>
		<% unless (@home_player_seasons_on_match[@obj] == nil) && (@away_player_seasons_on_match[@obj] == nil) %>
				<% if @home_player_seasons_on_match[@obj] != nil %>	
				<tr>			
					<td><%= link_to "#{@home_player_seasons_on_match[@obj].player.name}", player_path(@home_player_seasons_on_match[@obj].player) %> <%= link_to "#{@home_player_seasons_on_match[@obj].player.surname}", player_path(@home_player_seasons_on_match[@obj].player) %></td>
					<td style="max-width: 30px"><%= Goal.where(:player_season_id => @home_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj golova tog igraca na ovoj utakmici -->
					<td style="max-width: 30px"><%= Assist.where(:player_season_id => @home_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj asistencija tog igraca na ovoj utakmici -->
					<td style="max-width: 30px"><%= YellowCard.where(:player_season_id => @home_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj golova tog igraca na ovoj utakmici -->
					<td style="max-width: 30px"><%= RedCard.where(:player_season_id => @home_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj golova tog igraca na ovoj utakmici -->
				</tr>
				<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/matches/_players_on_match.html.erb
<% if @match.is_match_finished && (@home_player_seasons_on_match != nil && @away_player_seasons_on_match != nil) %>
	<!-- Nalazenje @max, koji predstavlja veci broj od broja igraca koji su dosli iz jednog i drugog tima -->
	<% if @home_player_seasons_on_match.size >= @away_player_seasons_on_match.size %>
		<% @max = @home_player_seasons_on_match.size %>
	<% elsif @home_player_seasons_on_match.size < @away_player_seasons_on_match.size %>
		<% @max = @away_player_seasons_on_match.size %>	
	<% end %>

	<!-- Stampanje igraca koji su dosli na utakmicu -->
	<% for @obj in 0..@max %>
		<% unless (@home_player_seasons_on_match[@obj] == nil) && (@away_player_seasons_on_match[@obj] == nil) %>
			<tr>
				<% if @home_player_seasons_on_match[@obj] != nil %>
					<td><%= Goal.where(:player_season_id => @home_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj golova tog igraca na ovoj utakmici -->
					<td><%= Assist.where(:player_season_id => @home_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj asistencija tog igraca na ovoj utakmici -->
					<td><%= YellowCard.where(:player_season_id => @home_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj golova tog igraca na ovoj utakmici -->
					<td><%= RedCard.where(:player_season_id => @home_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj golova tog igraca na ovoj utakmici -->
					<td style="min-width: 100px"><%= link_to "#{@home_player_seasons_on_match[@obj].player.name}", player_path(@home_player_seasons_on_match[@obj].player) %><br><%= link_to "#{@home_player_seasons_on_match[@obj].player.surname}", player_path(@home_player_seasons_on_match[@obj].player) %></td>
				<% else %>
					<td>	</td>
					<td>	</td>
					<td>	</td>
					<td>	</td>
					<td>	</td>
				<% end %>
				<% if @away_player_seasons_on_match[@obj] != nil %>				
					<td><%= link_to "#{@away_player_seasons_on_match[@obj].player.name}", player_path(@away_player_seasons_on_match[@obj].player) %><br><%= link_to "#{@away_player_seasons_on_match[@obj].player.surname}", player_path(@away_player_seasons_on_match[@obj].player) %></td>
					<td><%= Goal.where(:player_season_id => @away_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj golova tog igraca na ovoj utakmici -->
					<td><%= Assist.where(:player_season_id => @away_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj asistencija tog igraca na ovoj utakmici -->
					<td><%= YellowCard.where(:player_season_id => @away_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj golova tog igraca na ovoj utakmici -->
					<td><%= RedCard.where(:player_season_id => @away_player_seasons_on_match[@obj].id, :match_id => @match.id).count %></td> <!-- Broj golova tog igraca na ovoj utakmici -->
				<% else %>
					<td>	</td>
					<td>	</td>
					<td>	</td>
					<td>	</td>
					<td>	</td>
				<% end %>
			</tr>
		<% end %>
	<% end %>
<% end %>

app/views/matches/change_match_started.html.erb
<h1>Zdravo</h1>

app/views/matches/edit.html.erb
<h1>Matches#edit</h1>
<p>Find me in app/views/matches/edit.html.erb</p>

app/views/matches/new.html.erb
<h1>Matches#new</h1>
<p>Find me in app/views/matches/new.html.erb</p>

app/views/matches/temp.html.erb
<% for @obj in 0..30 %>
	<% unless (@home_player_seasons_on_match[@obj] == nil) && (@away_player_seasons_on_match[@obj] == nil) %>
		<tr>
			<% if @home_player_seasons_on_match[@obj] != nil %>
				<td><%= @home_player_seasons_on_match[@obj].player.full_name %></td>
			<% else %>
				<td>	</td>
			<% end %>
			<% if @away_player_seasons_on_match[@obj] != nil %>
				<td><%= @away_player_seasons_on_match[@obj].player.full_name %></td>
			<% else %>
				<td>	</td>
			<% end %>
		</tr>
	<% end %>
<% end %>